In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path
import sys

ROOT = Path.cwd().parent
sys.path.insert(0, str(ROOT))

from project_4 import backpropagation as nn

In [2]:
dataset_file = "rainfall_dataset.csv"
df = pd.read_csv(dataset_file)
df_norm = df.drop(df.columns[0], axis=1)

dataset_arr = df_norm.to_numpy()

print(df)

   Mnt/Yr   1997   1998   1999   2000   2001   2002   2003   2004   2005
0     Jan  106.2  181.0  315.0   59.0  216.5   90.8  169.4  138.8  189.1
1     Feb   96.6   50.2  268.8   86.7   15.1   78.5   85.7  200.8   43.9
2     Mar  134.4   29.4  196.9  182.2  158.0   96.5  162.6  237.9   62.5
3   April  109.8   35.3  322.0  115.0  164.8   73.4  285.3   88.5  168.2
4     Mei   80.9  133.5  302.6   60.3  252.8  195.2  245.7   68.0  229.5
5    Juni  175.3  144.6  256.2  191.1  306.7  191.7  196.3  200.5  174.0
6    Juli  225.8  213.0   29.9  121.9  121.3  139.2  312.1  206.8  210.8
7    Agts   95.7  381.0   78.6  342.6  417.6  156.3  282.0  204.3  145.7
8    Sept  290.6  170.8  407.2  451.1  395.7  382.5  561.5  475.3  290.5
9     Okt  391.1  340.3  204.1  367.5  733.0  363.8  471.9  377.5  175.5
10    Nop  265.4  275.8  126.4  108.0  467.6  164.3  125.4  141.2  206.4
11    Des  182.4  394.2  456.3  173.6  342.5  102.2  187.7  166.4  311.4


In [3]:
max_data = np.max(dataset_arr)
min_data = np.min(dataset_arr)

data_norm = 0.8 * (dataset_arr - min_data) / (max_data - min_data) + 0.1
data_cols = data_norm.shape[1]

data_in = data_norm[:, :data_cols-1]
target = data_norm[:, data_cols-1:].ravel()

input_row = data_in.shape[0]
input_col = data_in.shape[1]

print("========== Data Inputs ==========")
with np.printoptions(precision=3, suppress=True):
    print(data_in)

print("\n\n============ Targets ============")
with np.printoptions(precision=3, suppress=True):
    print(target.reshape(-1, 1))

========== Data Inputs ==========
[[0.202 0.285 0.434 0.149 0.324 0.184 0.272 0.238]
 [0.191 0.139 0.383 0.18  0.1   0.171 0.179 0.307]
 [0.233 0.116 0.303 0.286 0.259 0.191 0.264 0.348]
 [0.206 0.123 0.442 0.211 0.267 0.165 0.401 0.182]
 [0.173 0.232 0.42  0.15  0.365 0.301 0.357 0.159]
 [0.279 0.244 0.369 0.296 0.425 0.297 0.302 0.307]
 [0.335 0.321 0.116 0.219 0.218 0.238 0.431 0.314]
 [0.19  0.508 0.171 0.465 0.549 0.257 0.397 0.311]
 [0.407 0.274 0.537 0.586 0.524 0.509 0.709 0.613]
 [0.519 0.462 0.311 0.493 0.9   0.489 0.609 0.504]
 [0.379 0.391 0.224 0.204 0.604 0.266 0.223 0.241]
 [0.286 0.522 0.592 0.277 0.465 0.197 0.292 0.269]]


============ Targets ============
[[0.294]
 [0.132]
 [0.153]
 [0.271]
 [0.339]
 [0.277]
 [0.318]
 [0.246]
 [0.407]
 [0.279]
 [0.313]
 [0.43 ]]


In [4]:
ALPHA       = 0.9
MU          = 0.5
MAX_EPOCH   = 100000

NUM_LAYERS  = 2
NUM_NEURONS = [6, 1]

In [5]:
layers = [[] for _ in range(NUM_LAYERS)]
for i in range(NUM_LAYERS):
    if i == 0:
        layers[i] = nn.Layer(NUM_NEURONS[i], input_col, i)
        layers[i].nguyen_widrow_init()

    elif i == NUM_LAYERS - 1:
        layers[i] = nn.Layer(1, NUM_NEURONS[i-1], i)

    else:
        layers[i] = nn.Layer(NUM_NEURONS[i], NUM_NEURONS[i-1], i)

    layers[i].get_info()


===== LAYER to 0 =====
Num Neurons	: 6
Num Inputs	: 8

--- Neuron 0 ---
Weight	: [-0.06634182  0.13376979 -0.50475692 -0.32856853  0.17737644 -0.09933997
  0.38055999 -0.44238251]
Bias	: -0.8221194012905553

--- Neuron 1 ---
Weight	: [-0.06634182  0.13376979 -0.50475692 -0.32856853  0.17737644 -0.09933997
  0.38055999 -0.44238251]
Bias	: -0.20206256937223654

--- Neuron 2 ---
Weight	: [-0.06634182  0.13376979 -0.50475692 -0.32856853  0.17737644 -0.09933997
  0.38055999 -0.44238251]
Bias	: 0.4679509463195143

--- Neuron 3 ---
Weight	: [-0.06634182  0.13376979 -0.50475692 -0.32856853  0.17737644 -0.09933997
  0.38055999 -0.44238251]
Bias	: -0.602514282337536

--- Neuron 4 ---
Weight	: [-0.06634182  0.13376979 -0.50475692 -0.32856853  0.17737644 -0.09933997
  0.38055999 -0.44238251]
Bias	: -0.6685994005585599

--- Neuron 5 ---
Weight	: [-0.06634182  0.13376979 -0.50475692 -0.32856853  0.17737644 -0.09933997
  0.38055999 -0.44238251]
Bias	: 0.16552244749160538



===== LAYER to 1 =====
Nu

In [ ]:
epochs = 0
mse_acc = []
epochs_acc = []

stop_train = False

while True:
    epochs += 1

    error = np.zeros(input_row)
    output = np.zeros(input_row)

    for i in range(input_row):
        net_out = [[] for _ in range(NUM_LAYERS)]
        for j in range(NUM_LAYERS):
            if j == 0:
                net_out[j] = layers[j].forward_prop(data_in[i])

            else:
                net_out[j] = layers[j].forward_prop(net_out[j-1])

        error[i] = target[i] - net_out[NUM_LAYERS - 1][0]

        backprop_err = [[] for _ in range(NUM_LAYERS)]
        for j in range(NUM_LAYERS):
            rev_count = NUM_LAYERS - j

            if j == 0:
                backprop_err[j] = layers[rev_count - 1].back_prop(np.array([error[i]]), ALPHA, net_out[rev_count - 2], MU)

            elif j == NUM_LAYERS - 1:
                backprop_err[j] = layers[rev_count - 1].back_prop(backprop_err[j-1], ALPHA, data_in[i], MU)

            else:
                backprop_err[j] = layers[rev_count - 1].back_prop(backprop_err[j-1], ALPHA, net_out[rev_count - 2], MU)
                
    mse = nn.evaluate(error)
    print(f"\033[2K\rEpoch to {epochs}\n"
            f"\033[2K\rMSE\t: {mse:.7f}\n"
            f"\033[2K\rTarget\t: Inf")

    if nn.is_save(epochs):
        epochs_acc.append(epochs)
        mse_acc.append(mse)

    # if mse <= MIN_ERROR:
    #     stop_train = True

    if MAX_EPOCH and epochs >= MAX_EPOCH:
        stop_train = True

    if stop_train:
        break
    else:
        if nn.is_save(epochs):
            print("")
        else:
            print("\033[3A", end="")

NameError: name 'alpha' is not defined

In [1]:
import time

val1 = 0
val2 = 0
val3 = 0

while True:
    print(f"\033[2K\rVal 1: {val1}")
    print(f"\033[2K\rVal 2: {val2}")
    print(f"\033[2K\rVal 3: {val3}")

    val1 += 1
    val2 += 2
    val3 += 3

    time.sleep(0.1)

    print("\033[3A", end="")

Val 1: 0
Val 2: 0
Val 3: 0
Val 1: 1
Val 2: 2
Val 3: 3
Val 1: 2
Val 2: 4
Val 3: 6
Val 1: 3
Val 2: 6
Val 3: 9
Val 1: 4
Val 2: 8
Val 3: 12
Val 1: 5
Val 2: 10
Val 3: 15
Val 1: 6
Val 2: 12
Val 3: 18
Val 1: 7
Val 2: 14
Val 3: 21
Val 1: 8
Val 2: 16
Val 3: 24
Val 1: 9
Val 2: 18
Val 3: 27
Val 1: 10
Val 2: 20
Val 3: 30
Val 1: 11
Val 2: 22
Val 3: 33
Val 1: 12
Val 2: 24
Val 3: 36
Val 1: 13
Val 2: 26
Val 3: 39
Val 1: 14
Val 2: 28
Val 3: 42
Val 1: 15
Val 2: 30
Val 3: 45
Val 1: 16
Val 2: 32
Val 3: 48
Val 1: 17
Val 2: 34
Val 3: 51
Val 1: 18
Val 2: 36
Val 3: 54
Val 1: 19
Val 2: 38
Val 3: 57
Val 1: 20
Val 2: 40
Val 3: 60
Val 1: 21
Val 2: 42
Val 3: 63
Val 1: 22
Val 2: 44
Val 3: 66
Val 1: 23
Val 2: 46
Val 3: 69
Val 1: 24
Val 2: 48
Val 3: 72
Val 1: 25
Val 2: 50
Val 3: 75
Val 1: 26
Val 2: 52
Val 3: 78
Val 1: 27
Val 2: 54
Val 3: 81
Val 1: 28
Val 2: 56
Val 3: 84
Val 1: 29
Val 2: 58
Val 3: 87
Val 1: 30
Val 2: 60
Val 3: 90
Val 1: 31
Val 2: 62
Val 3: 93
Val 1: 32
Val 2: 64
Val 3: 96


KeyboardInterrupt: 